### ISSUE TITLE
Python error when running

### ISSUE THREAD

**Issue by patroza** [chetan/git-restore-mtime-action#10]
![88F0901A-03EE-4C64-BD37-D022B37052AB](https://user-images.githubusercontent.com/42661/124507746-c4d18900-ddce-11eb-8976-80271fe5b1a0.jpeg)

**Comment by patroza** [comment]
Appears to be a problem with running in python3 environment instead of 2.
The workaround appears to be running this beforehand:
```
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "2.x"
```
