### ISSUE TITLE
update to latest upstream version?

### ISSUE THREAD

**Issue by tenzap** [chetan/git-restore-mtime-action#20]
There is a newer release of git-restore-mtime
https://github.com/MestreLion/git-tools/releases

Would you update your action?

**Comment by p0358** [comment]
I ended up doing this on Windows runner instead:
```yaml
      - name: Add Python to PATH
        uses: actions/setup-python@v4

      - name: Restore git timestamps
        run: |
          $scriptpath = "${env:TEMP}".replace('\','\\') + "\\git-restore-mtime"
          C:\msys64\usr\bin\wget.exe -O ${scriptpath} https://raw.githubusercontent.com/MestreLion/git-tools/main/git-restore-mtime
          python ${scriptpath}
          git submodule foreach python "${scriptpath}"
```
